### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by j-justice** [karwosts/amex-offer-monitor#12]
I have this set to run as a cron job on my raspberrypi and it ran fine for months but now it doesn't (whether manually executed or from the Cron job).

I vaguely recall this happening a while back but I'm not completely sure if I had to start with a fresh config file or what.

I've not changed anything on the rpi that would prevent it from running and my password hasn't been changed on my credit card login either.

**Comment by karwosts** [comment]
There should be a log file in the install directory, does it look like it says anything interesting?

**Comment by j-justice** [comment]
@karwosts the most recent attempt has this in the log
`2020-07-05T11:00:05.237Z - info: Starting execution of amex-offer-monitor
2020-07-05T11:00:05.273Z - info: Logging into amex.com
2020-07-05T11:00:49.450Z - error:  message=.wait() for input[name="UserID"] timed out after 30000msec, stack=Error: .wait() for input[name="UserID"] timed out after 30000msec
    at newDone (/home/pi/Desktop/amex-offer-monitor-master/node_modules/nightmare/lib/actions.js:545:9)
    at Timeout._onTimeout (/home/pi/Desktop/amex-offer-monitor-master/node_modules/nightmare/lib/actions.js:578:5)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
`

**Comment by karwosts** [comment]
Can you update to the latest version of amex-offer-monitor.js? There was an amex website update back around Jun 5 which changed the login field name from UserID to eliloUserID, and it sounds like you don't have the update I made to fix that.

**Comment by j-justice** [comment]
That fixed it. Sorry I didn't try that first.

**Comment by j-justice** [comment]
@karwosts I upgraded my raspberrypi to a 4 and just set this up again. My old rpi could run this headless but for some reason that fails with this code. Am I missing something obvious? 

The only error in the log is below 
`2020-11-24T05:14:06.417Z - info: Starting execution of amex-offer-monitor
2020-11-24T05:14:06.429Z - info: Logging into amex.com`

I've tried running via SSH into the rpi from Windows directly and via Putty but both fail. It only seems to work via the terminal on the rpi via VNC (which allows Eletron to open). I can't figure out how to get this to run headless like I'd had it doing.

**Comment by graw0004** [comment]
@j-justice - did you figure this one out? I think I may be experiencing the same issue.

**Comment by j-justice** [comment]
@graw0004 I did not but I've not had time to dig into it further. I can't find my old SD card to see if my rpi is running with the same set up unfortunately

**Comment by graw0004** [comment]
Cool, thanks for the response. I'll play around with it more.

**Comment by j-justice** [comment]
@graw0004  is this still running for you? I'm getting an error like the initial one in this issue and I'm using the current version. I also checked the username/password variables and they've not changed.

**Comment by graw0004** [comment]
I was never able to get the email functionality working on my rpi, so I removed it. It's on the list to kick the tires on this again eventually, but haven't got back around to it.

**Comment by j-justice** [comment]
@graw0004 the email functionality usually works for me but I can't even get the script to run. Is it still running for you normally?

**Comment by graw0004** [comment]
I tried running it on rpi and a different Ubuntu machine and both are quickly stopping. Not seeing much information in the log. 
![image](https://user-images.githubusercontent.com/8103410/105606287-1379f200-5d5e-11eb-9900-21e9af16e0b8.png)

**Comment by figgarro** [comment]
> I tried running it on rpi and a different Ubuntu machine and both are quickly stopping. Not seeing much information in the log.
> ![image](https://user-images.githubusercontent.com/8103410/105606287-1379f200-5d5e-11eb-9900-21e9af16e0b8.png)

I'm having the same issue, anyone got it to work recently?  It works fine on my windows machine, but not Ubuntu.

**Comment by karwosts** [comment]
I just moved my setup from my windows machine to a headless proxmox/ubuntu lxc container. I was able to get this working in headless mode by doing the following (run after completing the initial install steps)

//Install XVFB
`sudo apt install xvfb`

//Install dependencies from [here ](https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300)
//I removed libgnome-keyring-dev from the list since apt told me it doesn't exist (?)
```
sudo apt-get install -y \
  xvfb \
  x11-xkb-utils \
  xfonts-100dpi \
  xfonts-75dpi \
  xfonts-scalable \
  xfonts-cyrillic \
  x11-apps \
  clang \
  libdbus-1-dev \
  libgtk2.0-dev \
  libnotify-dev \
  libgconf2-dev \
  libasound2-dev \
  libcap-dev \
  libcups2-dev \
  libxtst-dev \
  libxss1 \
  libnss3-dev \
  gcc-multilib \
  g++-multilib
```

Then finally running as:
`xvfb-run --server-args="-screen 0 1024x768x24" node amex-offer-monitor.js`

And that seemed to work. 

Closing this old issue, please reopen if you still have an issue.

**Comment by j-justice** [comment]
@karwosts I am still getting a fail to run for some reason, the log shows the same thing @figgarro screenshot above https://github.com/karwosts/amex-offer-monitor/issues/12#issuecomment-782906298

I went in and noted that the eliloUserID and eliloPassword as well as the loginSubmit page values are still the same so I am unsure why it would fail to continue to run.

**Comment by figgarro** [comment]
Try running this command, then running your jobs. 
```
Xvfb :99 &
export DISPLAY=:99
```
http://elementalselenium.com/tips/38-headless
