### ISSUE TITLE
Sits at Chase Logon Screen - Never logs in

### ISSUE THREAD

**Issue by Agile-Travel** [karwosts/amex-offer-monitor#13]
Fails at first stage of logon page.  Never enters any data.

Windows Node.Js 12.18.2 

PS - Amex offers works OK with same Node.JS build on Windows

**Comment by karwosts** [comment]
This tool doesn't support chase. IIRC someone forked a similar tool for chase, but that's somewhere else.

**Comment by Agile-Travel** [comment]
> This tool doesn't support chase. IIRC someone forked a similar tool for chase, but that's somewhere else.

Oops, sorry I got my Github links mixed up.   Wrong repo

Thank you, your solution is working splendid.
