### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by figgarro** [karwosts/amex-offer-monitor#19]
Anyone having issues with this recently?  I'm not able to get logged in when running it after it submits the username and password a page not found is returned.  The last time it successfully ran  for me was 7/15 around 6am.

**Comment by karwosts** [comment]
Yeah I see the same, looks like they changed something on the website. I'll take a look later and see if there's an easy fix.

**Comment by karwosts** [comment]
I had a successful run by replacing the line "const START = ..." with:

```
const START = "https://online.americanexpress.com/myca/logon/us/action/LogonHandler?request_type=LogonHandler&Face=en_US";
```

You can try that until I get an actual patch in.

**Comment by figgarro** [comment]
Thanks!

**Comment by karwosts** [comment]
Committed the change.
