### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by karwosts** [karwosts/amex-offer-monitor#2]
For the last two days, trying to login with this just leads me to a blank page that says:

"Unable to log you in at this time. Please contact american express customer service."

I can still login fine through a normal web browser. Seems like they have somehow flagged the electron browser or something to prevent it logging in.

**Comment by j-justice** [comment]
Same here, I get a message "logging into amex.com" message in the terminal and then it stops.

**Comment by karwosts** [comment]
I tried adding some additional delays during the login in case I was logging in too fast and tripping some kind of anti-automation check, that seems to have fixed it for me for now (or at least it went away from some other reason). You might try the version I updated today and see if that improves anything.

**Comment by j-justice** [comment]
I updated the code for the file "amex-offer-monitor.js" and it still says "logging into amex.com" and then terminates

**Comment by karwosts** [comment]
Hmm, I'm not sure. I can try to help but I'd need some more detailed information about what's going on.

- Did this work for you in the past, but then stopped working?
- What do you see on the browser window when it runs? Does it quit before or after it tries entering your uname/pass? If the window is closing too quickly to see what's happening, there's a --leaveopen flag you can add to the run which I think should cause it to not close the browser window when it finishes, which might give you more clues. 
- Pasting all the output you see on the console might be helpful.

**Comment by karwosts** [comment]
Not having this issue anymore. Reopen if it still happens.
