### ISSUE TITLE
stuck on Logging into amex.com

### ISSUE THREAD

**Issue by j-justice** [karwosts/amex-offer-monitor#22]
I am still running into the issue from #12 the error looks like this https://i.imgur.com/IirSoOJ.png where it just says logging into amex.com but nothing happens. I've tried the suggestions of @karwosts and @figgarro in that thread but still no luck. I've made sure all my packages installed are up to date too and also made sure that xvfb isn't running in the background from an old process.

**Comment by karwosts** [comment]
Sorry it's not working. I don't have any ideas off top of my head, but running with `--loglevel debug` may give more information. Also check the .log file output in the directory, it may also have additonal information that's not on the command line.

**Comment by j-justice** [comment]
I was able to do a clean install on Windows and it's working just fine
