### ISSUE TITLE
Password with '&' fails from command line

### ISSUE THREAD

**Issue by jeph36** [karwosts/amex-offer-monitor#5]
I have a password with an ampersand character '&' in it.  The command-line option interpreter treats this as some sort of break and consumes the password as only the characters prior to the '&' (and treats the characters after as an invalid command).  Note: the same password works fine when I use it from the config.yml file.

**Comment by karwosts** [comment]
This is not really related to this script but how your command line shell interprets ampersands. You'll need some combination of escape characters and/or quotation marks around the password.

If your password is "a&b", on windows maybe try --password a^&b (the carat escapes the ampersand). on linux, maybe try a\&b or "a&b", not exactly sure which will work.

**Comment by jeph36** [comment]
Yep, that worked.  On Linux, I tried both '\' and double quotes and both worked.
